[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "I"]

[tool.ruff.isort]
known-first-party = ["maze"] 